fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "christina@safetyay.com"
        sender_name: "brucelee"
    registration:
        form:
            type: App\Form\User\RegistrationType